global:
  scrape_interval: 5s # Scrape every 5 seconds
  scrape_timeout: 1s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - "api:3000"

